#!/usr/bin/env php
<?php

use jæm3l\CliNote\CliNote;
use jæm3l\CliNote\Slide\CanvasSlide;
use jæm3l\CliNote\Slide\CodeSlide;
use jæm3l\CliNote\Slide\ImageSlide;
use jæm3l\CliNote\Slide\ListSlide;
use jæm3l\CliNote\Slide\ProcessSlide;
use jæm3l\CliNote\Slide\TextSlide;
use jæm3l\CliNote\Slide\TitleSlide;
use Stoffel\Console\Canvas\Dimension;
use Stoffel\Console\Canvas\Element\Headline;
use Stoffel\Console\Canvas\Element\Image;
use Stoffel\Console\Canvas\Element\Rectangle;
use Stoffel\Console\Canvas\Fill;
use Stoffel\Console\Canvas\Position;

require dirname(__DIR__).'/vendor/autoload.php';

TitleSlide::setDefaultTitleFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');
TitleSlide::setDefaultSubtitleFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');
ListSlide::setHeadlineFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');
ListSlide::setBulletPointFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');

$cliNote = new CliNote(
    new TitleSlide('HELLO  CLI  NOTE', 'HELLO  CLI  BASED  PRESENTATIONS'),
    new TitleSlide('LIST  EXAMPLE'),
    new ListSlide('LIST  SLIDE', ['WITH', 'SOME', 'BULLETPOINTS']),
    new TitleSlide('TEXT  EXAMPLE'),
    new TextSlide(__DIR__.'/sample-text.txt'),
    new TitleSlide('IMAGE  EXAMPLE'),
    new ImageSlide(__DIR__.'/elephant.jpg'),
    new TitleSlide('PROCESS  EXAMPLE'),
    new ProcessSlide('ls -l', 'ls -l --color=always'),
    new TitleSlide('CODE  EXAMPLE'),
    new CodeSlide(__FILE__, 24, 34),
    new TitleSlide('CANVAS  EXAMPLE'),
    new class() extends CanvasSlide {
        protected function getBackground(): ?Fill
        {
            return Fill::withGradient('instagram');
        }

        protected function getElements(): array
        {
            return [
                [new Position(10, 5), new Rectangle(new Dimension(150, 10), Fill::withColor('#FFFFFF'))],
                [new Position(15, 7), new Headline('Hello World', Fill::withColor('#000000', '#FFFFFF'))],
                [new Position(10, 20), new Image(__DIR__.'/elephant.jpg', new Dimension(60, 50))],
                [new Position(90, 20), new Image(__DIR__.'/elephant.jpg', new Dimension(60, 50))],
            ];
        }
    },
    new TitleSlide('HAVE  FUN', 'POWERED  BY  JAEM3L'),
);
$cliNote->run();
