#!/usr/bin/env php
<?php

use jæm3l\CliNote\CliNote;
use jæm3l\CliNote\Slide\CanvasSlide;
use jæm3l\CliNote\Slide\CodeSlide;
use jæm3l\CliNote\Slide\ImageSlide;
use jæm3l\CliNote\Slide\TitleSlide;

require dirname(__DIR__).'/vendor/autoload.php';

TitleSlide::setTitleFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');
TitleSlide::setSubtitleFont(dirname(__DIR__).'/vendor/laminas/laminas-text/src/Figlet/laminas-project.flf');

$cliNote = new CliNote(
    new TitleSlide('HELLO  CLI  NOTE', 'HELLO  CLI  BASED  PRESENTATIONS'),
    new TitleSlide('IMAGE  EXAMPLE'),
    new ImageSlide(__DIR__.'/elephant.jpg'),
    new TitleSlide('CODE  EXAMPLE'),
    new CodeSlide(__FILE__, 14, 10),
    new TitleSlide('CANVAS  EXAMPLE'),
    new CanvasSlide(),
    new TitleSlide('HAVE  FUN', 'POWERED  BY  JAEM3L'),
);
$cliNote->run();
